[project]
name = "downbot"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.11.2",
    "python-dotenv>=1.1.1",
    "yt-dlp>=2025.7.21",
]
